# https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/ci-configurations/github-actions.md
name: "Release: @erosson/polynomial"
on:
  push:
    branches: [main, beta]
    paths: ["packages/polynomial/**"]

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    defaults:
      run:
        # set the directory for all steps below
        working-directory: packages/polynomial
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      # id-token: write # to enable use of OIDC for npm provenance
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - run: yarn
      - run: yarn test
      - run: yarn build
      - run: yarn multi-semantic-release
        working-directory: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        